// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spbs.Ui.Data;

#nullable disable

namespace Spbs.Ui.Data.Migrations.RecurringExpenses
{
    [DbContext(typeof(RecurringExpensesDbContext))]
    [Migration("20230204144901_Ignore-Users-Table")]
    partial class IgnoreUsersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Spbs.Ui.Features.RecurringExpenses.RecurringExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BillingPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("BillingType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwningUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("BillingDate");

                    b.HasIndex("Name");

                    b.HasIndex("OwningUserId");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("Spbs.Ui.Features.RecurringExpenses.RecurringExpenseHistoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Payed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("RecurringExpenseId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("RecurringExpenseId");

                    b.ToTable("RecurringExpenseHistoryItem");
                });

            modelBuilder.Entity("Spbs.Ui.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AzureAdId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("User", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Spbs.Ui.Features.RecurringExpenses.RecurringExpense", b =>
                {
                    b.HasOne("Spbs.Ui.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwningUserId")
                        .HasPrincipalKey("AzureAdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spbs.Ui.Features.RecurringExpenses.RecurringExpenseHistoryItem", b =>
                {
                    b.HasOne("Spbs.Ui.Features.RecurringExpenses.RecurringExpense", null)
                        .WithMany("PaymentHistory")
                        .HasForeignKey("RecurringExpenseId");
                });

            modelBuilder.Entity("Spbs.Ui.Features.RecurringExpenses.RecurringExpense", b =>
                {
                    b.Navigation("PaymentHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
