trigger:
- master
- development

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  
stages:
  - stage: Build
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: Build

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 7.x'
      inputs:
        packageType: 'sdk'
        version: 7.x
      
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: restore
        projects: '**/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'
    
    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: test
        projects: '**/*[Tt]ests/*.csproj'


#
#- ${{ if eq(variables.isMain, 'true') }}:
#  - task: PublishBuildArtifacts@1
#    inputs:
#      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#      ArtifactName: 'drop'
#      publishLocation: 'Container'