version: '3.8'

services: 
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: spbs_identity_db
    restart: always
    user: root
    environment:
      MSSQL_SA_PASSWORD: pAssw0rd
      MSSQL_PID: Express
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes: 
      - ~/apps/mssql/data:/var/opt/mssql/data
  mongo:
    image: mongo
    restart: always
    container_name: spbs_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pAssw0rd
      PUID: 1000
      PGID: 1000
    volumes:
      - ~/apps/mongodb:/data/db
    ports:
      - "27017:27017"